version: "3"
name: esgi-cluster

services:
  spark-master:
    image: bde2020/spark-master:3.2.0-hadoop3.2
    restart: always
    container_name: spark-master
    ports:
      - "10000:8080"
      - "7077:7077"
      - "4040:4040"
    environment:
      - "INIT_DAEMON_STEP=setup_spark"
    volumes:
      - ./app:/app

  spark-worker-1:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    restart: always
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./app:/app

  spark-worker-2:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    restart: always
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./app:/app

  spark-worker-3:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    restart: always
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./app:/app
